server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_health_twin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

aliyun:
  dashscope:
    api-key: ${API_KEY}
    base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    stream-chat-baseurl: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
    model-name: "qwen-plus"
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    bucket-name: "tlias399"
    region: "cn-hangzhou"
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
  ocr:
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    endpoint: "ocr-api.cn-hangzhou.aliyuncs.com"

#开启mybatis-plus的驼峰命名,以及开启mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smarthealth.domain.entity


